; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

define void @basic(i32 %a) {
; CHECK-LABEL: define void @basic(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = phi i32 [ [[A]], %[[LOOP_ROLLING_PRE]] ], [ [[A_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[A_NEXT]] = call i32 @foo(i32 [[TMP0]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:

  %a1 = call i32 @foo(i32 %a)
  %a2 = call i32 @foo(i32 %a1)
  %a3 = call i32 @foo(i32 %a2)
  %a4 = call i32 @foo(i32 %a3)

  ret void
}

@r0 = global i32 123
define ptr @global_initial_value(ptr %p) {
; CHECK-LABEL: define ptr @global_initial_value(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[EXTERNAL_ARRAY:%.*]] = alloca [4 x ptr], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = phi ptr [ @r0, %[[LOOP_ROLLING_PRE]] ], [ [[TMP1:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = add i32 [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    [[TMP1]] = call ptr @goo(ptr [[TMP0]], i32 [[TMP8]])
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [4 x ptr], ptr [[EXTERNAL_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    store ptr [[TMP1]], ptr [[TMP2]], align 8
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [4 x ptr], ptr [[EXTERNAL_ARRAY]], i32 0, i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
; CHECK-NEXT:    ret ptr [[TMP4]]
;
entry:

  %b1 = load i32, ptr %p
  %a1 = call ptr @goo(ptr @r0, i32 %b1)

  %bp2 = getelementptr i32, ptr %p, i32 1
  %b2 = load i32, ptr %bp2
  %a2 = call ptr @goo(ptr %a1, i32 %b2)

  %bp3 = getelementptr i32, ptr %p, i32 2
  %b3 = load i32, ptr %bp3
  %a3 = call ptr @goo(ptr %a2, i32 %b3)

  %bp4 = getelementptr i32, ptr %p, i32 3
  %b4 = load i32, ptr %bp4
  %a4 = call ptr @goo(ptr %a3, i32 %b4)

  ret ptr %a4
}

; I believe we could roll this, but we need to construct the correct alignment graph
define void @multiple_dependencies(ptr %a) {
; CHECK-LABEL: define void @multiple_dependencies(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[A]], align 4
; CHECK-NEXT:    [[CALL:%.*]] = call ptr @goo(ptr [[TMP2]], ptr [[A]])
; CHECK-NEXT:    store ptr [[CALL]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[CALL]], align 4
; CHECK-NEXT:    [[CALL1:%.*]] = call ptr @goo(ptr [[TMP1]], ptr [[A]])
; CHECK-NEXT:    store ptr [[CALL1]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[CALL1]], align 4
; CHECK-NEXT:    [[CALL2:%.*]] = call ptr @goo(ptr [[TMP3]], ptr [[A]])
; CHECK-NEXT:    store ptr [[CALL2]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
entry:

  %0 = load ptr, ptr %a, align 4
  %call = call ptr @goo(ptr %0, ptr %a)
  store ptr %call, ptr %a, align 4

  %1 = load ptr, ptr %call, align 4
  %call1 = call ptr @goo(ptr %1, ptr %a)
  store ptr %call1, ptr %a, align 4

  %2 = load ptr, ptr %call1, align 4
  %call2 = call ptr @goo(ptr %2, ptr %a)
  store ptr %call2, ptr %a, align 4

  ret void
}

declare i32 @foo(i32 %a)
declare ptr @goo(ptr %a, i32 %b)
