; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

; Test we put the alloca in the function entry rather than inside a loop
define void @no_alloca_in_loop() {
; CHECK-LABEL: define void @no_alloca_in_loop() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[EXTERNAL_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @foo(i32 [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[EXTERNAL_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x i32], ptr [[EXTERNAL_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
; CHECK-NEXT:    call void @bar(i32 [[TMP5]])
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE]]
;
entry:
  br label %loop
loop:
  %a = call i32 @foo(i32 0)
  %b = call i32 @foo(i32 1)
  %c = call i32 @foo(i32 2)

  call void @bar(i32 %c)

  br label %loop
}


declare i32 @foo(i32)
declare void @bar(i32)
