; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

; Basic case for GEP zero
define dso_local void @basic_gep_zero(ptr noundef %x.addr) {
; CHECK-LABEL: define dso_local void @basic_gep_zero(
; CHECK-SAME: ptr noundef [[X_ADDR:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i32 [[TMP2]]
; CHECK-NEXT:    call void @bar(ptr noundef [[TMP3]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = load ptr, ptr %x.addr, align 8
  call void @bar(ptr noundef %0)

  %1 = load ptr, ptr %x.addr, align 8
  %add.ptr1 = getelementptr inbounds i32, ptr %1, i32 1
  call void @bar(ptr noundef %add.ptr1)

  %2 = load ptr, ptr %x.addr, align 8
  %add.ptr2 = getelementptr inbounds i32, ptr %2, i32 2
  call void @bar(ptr noundef %add.ptr2)

  ret void
}

; Test for chained GEP zero
define dso_local void @chained_gep_zero() {
; CHECK-LABEL: define dso_local void @chained_gep_zero() {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca i32, align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[TMP1]], i32 -1
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i32 1
; CHECK-NEXT:    store i32 -1, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 2
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %a = alloca i32, align 4

  %p1 = getelementptr i8, ptr %a, i32 1
  %p2 = getelementptr i8, ptr %p1, i32 -1
  %p3 = getelementptr i8, ptr %p2, i32 1
  store i32 -1, ptr %p3

  %p4 = getelementptr i8, ptr %a, i32 1
  %p5 = getelementptr i8, ptr %p4, i32 -1
  %p6 = getelementptr i8, ptr %p5, i32 1
  store i32 -1, ptr %p6

  ret void
}

; Test for decreasing GEP zero
define dso_local void @decreasing_gep_zero(ptr noundef %x.addr) {
; CHECK-LABEL: define dso_local void @decreasing_gep_zero(
; CHECK-SAME: ptr noundef [[X_ADDR:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = mul i32 [[IV]], -1
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i32 [[TMP2]]
; CHECK-NEXT:    call void @bar(ptr noundef [[TMP3]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = load ptr, ptr %x.addr, align 8
  %add.ptr0 = getelementptr inbounds i32, ptr %0, i32 1
  call void @bar(ptr noundef %add.ptr0)

  %1 = load ptr, ptr %x.addr, align 8
  call void @bar(ptr noundef %1)

  %2 = load ptr, ptr %x.addr, align 8
  %add.ptr2 = getelementptr inbounds i32, ptr %2, i32 -1
  call void @bar(ptr noundef %add.ptr2)

  ret void
}

; Test for double GEP zero
define dso_local void @double_gep_zero(ptr noundef %p) {
; CHECK-LABEL: define dso_local void @double_gep_zero(
; CHECK-SAME: ptr noundef [[P:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[P]], i32 [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = mul i32 [[IV]], 2
; CHECK-NEXT:    [[TMP4:%.*]] = add i32 [[TMP3]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[TMP2]], i32 [[TMP4]]
; CHECK-NEXT:    store i32 -1, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  store i32 -1, ptr %p

  %p0 = getelementptr i8, ptr %p, i32 1
  %p1 = getelementptr i8, ptr %p0, i32 2
  store i32 -1, ptr %p1

  %p2 = getelementptr i8, ptr %p, i32 2
  %p3 = getelementptr i8, ptr %p2, i32 4
  store i32 -1, ptr %p3

  ret void
}

; Test for multiple operand GEP zero
define dso_local void @mutiple_operand_gep_zero() {
; CHECK-LABEL: define dso_local void @mutiple_operand_gep_zero() {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca [2 x [3 x i32]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [2 x [3 x i32]], ptr [[TMP0]], i32 0, i32 0, i32 [[TMP2]]
; CHECK-NEXT:    call void @bar(ptr noundef [[TMP3]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %a = alloca [2 x [3 x i32]], align 4
  call void @bar(ptr noundef %a)

  %arrayidx1 = getelementptr inbounds [2 x [3 x i32]], ptr %a, i32 0, i32 0, i32 1
  call void @bar(ptr noundef %arrayidx1)

  %arrayidx2 = getelementptr inbounds [2 x [3 x i32]], ptr %a, i32 0, i32 0, i32 2
  call void @bar(ptr noundef %arrayidx2)

  ret void
}

; Test for GEP zero but operands do not form a monotonic sequence
define dso_local void @gep_zero_not_special_seq(ptr noundef %x) {
; CHECK-LABEL: define dso_local void @gep_zero_not_special_seq(
; CHECK-SAME: ptr noundef [[X:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [4 x i32], ptr @integer_sequence_array, i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i32 [[TMP2]]
; CHECK-NEXT:    call void @bar(ptr noundef [[TMP3]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = load ptr, ptr %x, align 8

  %add.ptr1 = getelementptr inbounds i32, ptr %0, i32 2
  %add.ptr2 = getelementptr inbounds i32, ptr %0, i32 4
  %add.ptr3 = getelementptr inbounds i32, ptr %0, i32 7

  call void @bar(ptr noundef %0)
  call void @bar(ptr noundef %add.ptr1)
  call void @bar(ptr noundef %add.ptr2)
  call void @bar(ptr noundef %add.ptr3)

  ret void
}

; Test when GEP instruction accesses different types but same base
define dso_local void @gep_diff_type_same_base(ptr noundef %x.addr) {
; CHECK-LABEL: define dso_local void @gep_diff_type_same_base(
; CHECK-SAME: ptr noundef [[X_ADDR:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x ptr], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [4 x i32], ptr [[X_ADDR]], i32 1, i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [4 x i32], ptr [[X_ADDR]], i32 1, i32 1
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[X_ADDR]], i32 2
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store ptr [[TMP2]], ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP4]], ptr [[TMP5]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
; CHECK-NEXT:    call void @bar(ptr noundef [[TMP7]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %add.ptr0 = getelementptr inbounds [4 x i32], ptr %x.addr, i32 1, i32 0
  call void @bar(ptr noundef %add.ptr0)

  %add.ptr1 = getelementptr inbounds [4 x i32], ptr %x.addr, i32 1, i32 1
  call void @bar(ptr noundef %add.ptr1)

  %add.ptr2 = getelementptr inbounds i32, ptr %x.addr, i32 2
  call void @bar(ptr noundef %add.ptr2)

  ret void
}

; The mismatching array must store both the constant and the argument
define dso_local void @gep_constant_and_argument(ptr noundef %x.addr, i32 noundef %a) {
; CHECK-LABEL: define dso_local void @gep_constant_and_argument(
; CHECK-SAME: ptr noundef [[X_ADDR:%.*]], i32 noundef [[A:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [2 x i32], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [2 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i32 0, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [2 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[A]], ptr [[TMP2]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [2 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i32 [[TMP4]]
; CHECK-NEXT:    call void @bar(ptr noundef [[TMP5]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 2
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = load ptr, ptr %x.addr, align 8
  call void @bar(ptr noundef %0)

  %add.ptr1 = getelementptr inbounds i32, ptr %0, i32 %a
  call void @bar(ptr noundef %add.ptr1)

  ret void
}

declare void @bar(ptr noundef)
