; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

%A = type { [4 x i32], [4 x i32], [4 x i32] }
%B = type { [5 x i32], [5 x i32], [5 x i32] }
%C = type { i32, i32, i32 }
@my_array = global [4 x i32] [i32 10, i32 20, i32 30, i32 40]

; Function that takes a pointer to MyStruct
;.
; CHECK: @my_array = global [4 x i32] [i32 10, i32 20, i32 30, i32 40]
; CHECK: @integer_sequence_array = internal constant [4 x ptr] [ptr @my_array, ptr getelementptr inbounds (i32, ptr @my_array, i32 1), ptr getelementptr inbounds (i32, ptr @my_array, i32 2), ptr getelementptr inbounds (i32, ptr @my_array, i32 3)]
; CHECK: @integer_sequence_array.1 = internal constant [3 x ptr] [ptr @my_array, ptr getelementptr inbounds (i32, ptr @my_array, i32 1), ptr getelementptr inbounds (i32, ptr @my_array, i32 2)]
;.
define void @gep_mismatching_type(ptr %p) {
; CHECK-LABEL: define void @gep_mismatching_type(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [[A:%.*]], ptr [[TMP0]], i32 0
; CHECK-NEXT:    call void @bar(ptr [[TMP3]])
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    [[ADD_PTR1:%.*]] = getelementptr inbounds [[B:%.*]], ptr [[TMP1]], i32 1
; CHECK-NEXT:    call void @bar(ptr [[ADD_PTR1]])
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    [[ADD_PTR2:%.*]] = getelementptr inbounds [[A]], ptr [[TMP2]], i32 2
; CHECK-NEXT:    call void @bar(ptr [[ADD_PTR2]])
; CHECK-NEXT:    ret void
;
entry:
  %0 = load ptr, ptr %p, align 8
  %add.ptr0 = getelementptr inbounds %A, ptr %0, i32 0
  call void @bar(ptr %add.ptr0)

  %1 = load ptr, ptr %p, align 8
  %add.ptr1 = getelementptr inbounds %B, ptr %1, i32 1
  call void @bar(ptr %add.ptr1)

  %2 = load ptr, ptr %p, align 8
  %add.ptr2 = getelementptr inbounds %A, ptr %2, i32 2
  call void @bar(ptr %add.ptr2)

  ret void
}


define void @constant_expr(i32 %val) {
; CHECK-LABEL: define void @constant_expr(
; CHECK-SAME: i32 [[VAL:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = mul i32 [[IV]], 2
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [4 x i32], ptr @my_array, i32 [[TMP1]]
; CHECK-NEXT:    store i32 [[VAL]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  store i32 %val, ptr @my_array

  store i32 %val, ptr getelementptr inbounds ([4 x i32], ptr @my_array, i32 2)

  %add2 = getelementptr inbounds [4 x i32], ptr @my_array, i32 4
  store i32 %val, ptr %add2
  ret void
}


define void @constant_expr_store() {
; CHECK-LABEL: define void @constant_expr_store() {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr [4 x ptr], ptr @integer_sequence_array, i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    store i32 4, ptr [[TMP2]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  store i32 4, ptr @my_array, align 1

  store i32 4, ptr getelementptr inbounds (i32, ptr @my_array, i32 1), align 1
  store i32 4, ptr getelementptr inbounds (i32, ptr @my_array, i32 2), align 1
  store i32 4, ptr getelementptr inbounds (i32, ptr @my_array, i32 3), align 1

  ret void
}

define void @constant_expr_call() {
; CHECK-LABEL: define void @constant_expr_call() {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr [3 x ptr], ptr @integer_sequence_array.1, i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    call void @bar(ptr [[TMP2]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  call void @bar(ptr @my_array)
  call void @bar(ptr getelementptr inbounds (i32, ptr @my_array, i32 1))
  call void @bar(ptr getelementptr inbounds (i32, ptr @my_array, i32 2))

  ret void
}

define void @gep_mismatching_external_value(ptr %x, ptr %y) {
; CHECK-LABEL: define void @gep_mismatching_external_value(
; CHECK-SAME: ptr [[X:%.*]], ptr [[Y:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[Y]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @baz(ptr [[TMP0]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @baz(ptr [[TMP1]])
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i32 0, ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[TMP5]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i32 [[TMP8]]
; CHECK-NEXT:    call void @bar(ptr [[TMP9]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = load ptr, ptr %x, align 8
  %1 = load ptr, ptr %y, align 8

  %a = call i32 @baz(ptr %0)
  %b = call i32 @baz(ptr %1)

  %add.ptr1 = getelementptr inbounds i32, ptr %0, i32 %a
  %add.ptr2 = getelementptr inbounds i32, ptr %0, i32 %b

  call void @bar(ptr %0)
  call void @bar(ptr %add.ptr1)
  call void @bar(ptr %add.ptr2)

  ret void
}

define void @non_constant_geps_to_structs(ptr %p) {
; CHECK-LABEL: define void @non_constant_geps_to_structs(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x ptr], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[C:%.*]], ptr [[P]], i32 0, i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [[C]], ptr [[P]], i32 0, i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [[C]], ptr [[P]], i32 0, i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store ptr [[TMP1]], ptr [[TMP4]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP2]], ptr [[TMP5]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[TMP6]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[TMP9]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
  %1 = getelementptr inbounds %C, ptr %p, i32 0, i32 0
  store i32 1, ptr %1

  %2 = getelementptr inbounds %C, ptr %p, i32 0, i32 1
  store i32 2, ptr %2

  %3 = getelementptr inbounds %C, ptr %p, i32 0, i32 2
  store i32 3, ptr %3

  ret void
}

declare void @bar(ptr)
declare void @baz(ptr)
