; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s


;.
; CHECK: @integer_sequence_array = internal constant [3 x i32] [i32 1, i32 2, i32 5]
;.
define dso_local void @foo(i32 noundef %a, i32 noundef %b, i32 noundef %c) {
; CHECK-LABEL: define dso_local void @foo(
; CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i32 [[A]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = mul i32 [[TMP0]], 3
; CHECK-NEXT:    [[TMP4:%.*]] = add nsw i32 [[C]], 9
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[TMP5]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr [3 x i32], ptr @integer_sequence_array, i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP8]], align 4
; CHECK-NEXT:    call void @bar(i32 noundef [[TMP7]], i32 [[TMP9]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %tmp1 = add nsw i32 %a, 1
  %tmp2 = mul i32 %tmp1, 3
  %tmp3 = add nsw i32 %c, 9

  call void @bar(i32 noundef %tmp1, i32 1)
  call void @bar(i32 noundef %tmp2, i32 2)
  call void @bar(i32 noundef %tmp3, i32 5)
  ret void
}

declare void @bar(i32 noundef, i32 noundef) #1
