; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling -loop-rolling-ignore-cost < %s | FileCheck %s --check-prefix=CHECK-ORDER

; alloca instructions cannot be identical because they should not be moved to the body of the loop
define void @identical_alloca() {
; CHECK-ORDER-LABEL: define void @identical_alloca() {
; CHECK-ORDER-NEXT:  [[ENTRY:.*:]]
; CHECK-ORDER-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK-ORDER-NEXT:    [[B:%.*]] = alloca i32, align 4
; CHECK-ORDER-NEXT:    [[C:%.*]] = alloca i32, align 4
; CHECK-ORDER-NEXT:    call void @bar(ptr [[A]])
; CHECK-ORDER-NEXT:    call void @bar(ptr [[B]])
; CHECK-ORDER-NEXT:    call void @bar(ptr [[C]])
; CHECK-ORDER-NEXT:    ret void
;
entry:
  %a = alloca i32
  %b = alloca i32
  %c = alloca i32
  call void @bar(ptr %a)
  call void @bar(ptr %b)
  call void @bar(ptr %c)

  ret void
}

define void @identical_seeds(ptr %a) {
; CHECK-ORDER-LABEL: define void @identical_seeds(
; CHECK-ORDER-SAME: ptr [[A:%.*]]) {
; CHECK-ORDER-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-ORDER-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK-ORDER:       [[LOOP_ROLLING_BODY]]:
; CHECK-ORDER-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-ORDER-NEXT:    call void @bar(ptr [[A]])
; CHECK-ORDER-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-ORDER-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-ORDER-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK-ORDER:       [[LOOP_ROLLING_EXIT]]:
; CHECK-ORDER-NEXT:    ret void
;
entry:
  call void @bar(ptr %a)
  call void @bar(ptr %a)
  call void @bar(ptr %a)

  ret void
}

declare void @bar(ptr %a)
