; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling -loop-rolling-ignore-cost < %s | FileCheck %s --check-prefix=CHECK-ORDER

define void @foo(ptr %x.addr) {
; CHECK-ORDER-LABEL: define void @foo(
; CHECK-ORDER-SAME: ptr [[X_ADDR:%.*]]) {
; CHECK-ORDER-NEXT:  [[ENTRY:.*:]]
; CHECK-ORDER-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8
; CHECK-ORDER-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK-ORDER:       [[LOOP_ROLLING_PRE]]:
; CHECK-ORDER-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK-ORDER:       [[LOOP_ROLLING_BODY]]:
; CHECK-ORDER-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-ORDER-NEXT:    [[TMP1:%.*]] = mul i32 [[IV]], 1
; CHECK-ORDER-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 0
; CHECK-ORDER-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i32 [[TMP2]]
; CHECK-ORDER-NEXT:    call void @bar(ptr [[TMP3]])
; CHECK-ORDER-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-ORDER-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-ORDER-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK-ORDER:       [[LOOP_ROLLING_EXIT]]:
; CHECK-ORDER-NEXT:    ret void
;
entry:
  %0 = load ptr, ptr %x.addr, align 8
  br label %start

start:
  call void @bar(ptr %0)

  %add.ptr1 = getelementptr inbounds i32, ptr %0, i32 1
  call void @bar(ptr %add.ptr1)

  %add.ptr2 = getelementptr inbounds i32, ptr %0, i32 2
  call void @bar(ptr %add.ptr2)

  ret void
}

declare void @bar(ptr)
