; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

define void @sext_integer(i8 %x, i8 %y) {
; CHECK-LABEL: define void @sext_integer(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [2 x i8], align 1
; CHECK-NEXT:    [[TMP0:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [2 x i8], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i8 [[X]], ptr [[TMP1]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [2 x i8], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i8 [[Y]], ptr [[TMP2]], align 1
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[IV_TRUNC:%.*]] = trunc i32 [[IV]] to i8
; CHECK-NEXT:    [[TMP5:%.*]] = mul i8 [[IV_TRUNC]], -18
; CHECK-NEXT:    [[TMP6:%.*]] = add i8 [[TMP5]], 10
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr [2 x i8], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[TMP11]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ult i8 [[TMP4]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = mul i32 [[IV]], 2
; CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[TMP8]], 0
; CHECK-NEXT:    [[TMP10:%.*]] = select i1 [[TMP7]], i32 1, i32 [[TMP9]]
; CHECK-NEXT:    store i32 [[TMP10]], ptr [[TMP0]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 2
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %a = alloca i32, align 4
  %cmp1 = icmp ult i8 %x, 10
  %cmp2 = icmp ult i8 %y, -8

  %cond1 = select i1 %cmp1, i32 1, i32 0
  %cond2 = select i1 %cmp2, i32 1, i32 2

  store i32 %cond1, ptr %a, align 4
  store i32 %cond2, ptr %a, align 4

  ret void
}

define void @trunc_integer(i64 %x, i64 %y) {
; CHECK-LABEL: define void @trunc_integer(
; CHECK-SAME: i64 [[X:%.*]], i64 [[Y:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [2 x i64], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [2 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i64 [[X]], ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [2 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i64 [[Y]], ptr [[TMP2]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[IV_SEXT:%.*]] = sext i32 [[IV]] to i64
; CHECK-NEXT:    [[TMP5:%.*]] = mul i64 [[IV_SEXT]], -18
; CHECK-NEXT:    [[TMP6:%.*]] = add i64 [[TMP5]], 10
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr [2 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr [[TMP11]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ult i64 [[TMP4]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = mul i32 [[IV]], 2
; CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[TMP8]], 0
; CHECK-NEXT:    [[TMP10:%.*]] = select i1 [[TMP7]], i32 1, i32 [[TMP9]]
; CHECK-NEXT:    store i32 [[TMP10]], ptr [[TMP0]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 2
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %a = alloca i32, align 4
  %cmp1 = icmp ult i64 %x, 10
  %cmp2 = icmp ult i64 %y, -8

  %cond1 = select i1 %cmp1, i32 1, i32 0
  %cond2 = select i1 %cmp2, i32 1, i32 2

  store i32 %cond1, ptr %a, align 4
  store i32 %cond2, ptr %a, align 4

  ret void
}

define void @basic_integer_seq(ptr %x.addr) {
; CHECK-LABEL: define void @basic_integer_seq(
; CHECK-SAME: ptr [[X_ADDR:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[IV_SEXT:%.*]] = sext i32 [[IV]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[IV_SEXT]], 2
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[TMP2]]
; CHECK-NEXT:    call void @bar(ptr [[TMP3]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:

  %0 = load ptr, ptr %x.addr, align 8
  %add.ptr = getelementptr inbounds i32, ptr %0, i64 1
  call void @bar(ptr %add.ptr)

  %add.ptr1 = getelementptr inbounds i32, ptr %0, i64 3
  call void @bar(ptr %add.ptr1)

  %add.ptr2 = getelementptr inbounds i32, ptr %0, i64 5
  call void @bar(ptr %add.ptr2)

  %add.ptr3 = getelementptr inbounds i32, ptr %0, i64 7
  call void @bar(ptr %add.ptr3)

  ret void
}

declare void @bar(ptr)
