; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

; Invalid scheduling since there is a store instruction between iteration -> affect the value of the load instruction

define void @store_between_iterations(ptr %a.addr) {
; CHECK-LABEL: define void @store_between_iterations(
; CHECK-SAME: ptr [[A_ADDR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    call void @bar(i32 [[TMP0]], i32 0)
; CHECK-NEXT:    store i32 1, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    call void @bar(i32 [[TMP1]], i32 1)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[A_ADDR]], align 4
; CHECK-NEXT:    call void @bar(i32 [[TMP2]], i32 2)
; CHECK-NEXT:    ret void
;
entry:
  %0 = load i32, ptr %a.addr, align 4
  call void @bar(i32 %0, i32 0)

  store i32 1, ptr %a.addr, align 4

  %1 = load i32, ptr %a.addr, align 4
  call void @bar(i32 %1, i32 1)

  %2 = load i32, ptr %a.addr, align 4
  call void @bar(i32 %2, i32 2)

  ret void
}

define void @header_deps(i32 %a) {
; CHECK-LABEL: define void @header_deps(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[A]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = mul i32 [[TMP0]], 2
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 3
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = add i32 [[TMP3]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = add i32 [[TMP2]], [[TMP4]]
; CHECK-NEXT:    call void @goo(i32 [[TMP5]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = add i32 %a, 1
  %1 = mul i32 %0, 2
  %2 = add i32 %1, 3

  %3 = add i32 %2, 1
  call void @goo(i32 %3)
  %4 = add i32 %2, 2
  call void @goo(i32 %4)
  %5 = add i32 %2, 3
  call void @goo(i32 %5)

  ret void
}


define void @side_effects(ptr %a, ptr %b) {
; CHECK-LABEL: define void @side_effects(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[A]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr ptr, ptr [[A]], i32 0
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[TMP7]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr ptr, ptr [[A]], i32 1
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[TMP3]], align 4
; CHECK-NEXT:    ret void
;
entry:

  %0 = load i32, ptr %a
  %1 = load i32, ptr %b

  %2 = getelementptr ptr, ptr %a, i32 0
  store i32 %1, ptr %2

  %3 = getelementptr ptr, ptr %a, i32 1
  store i32 %0, ptr %3

  ret void
}

define void @invalid_dependency(i32 %val) {
; CHECK-LABEL: define void @invalid_dependency(
; CHECK-SAME: i32 [[VAL:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = mul i32 [[VAL]], 2
; CHECK-NEXT:    [[B:%.*]] = add i32 [[A]], 3
; CHECK-NEXT:    [[A1:%.*]] = add i32 [[A]], 1
; CHECK-NEXT:    call void @bar(i32 [[A1]], i32 [[B]])
; CHECK-NEXT:    [[TMP3:%.*]] = sub i32 [[A1]], 1
; CHECK-NEXT:    [[C2:%.*]] = add i32 [[A1]], 2
; CHECK-NEXT:    call void @bar(i32 [[C2]], i32 [[TMP3]])
; CHECK-NEXT:    ret void
;
entry:
  %a = mul i32 %val, 2
  %b = add i32 %a, 3

  %a1 = add i32 %a, 1
  call void @bar(i32 %a1, i32 %b)

  %d = sub i32 %a1, 1
  %c2 = add i32 %a1, 2
  call void @bar(i32 %c2, i32 %d)

  ret void
}

declare void @bar(i32, i32)
declare void @goo(i32)
