; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

define void @multiple_value_uses(i1 %cond, ptr %b, ptr %c) {
; CHECK-LABEL: define void @multiple_value_uses(
; CHECK-SAME: i1 [[COND:%.*]], ptr [[B:%.*]], ptr [[C:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [4 x ptr], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[COND]], ptr [[B]], ptr [[C]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 3
; CHECK-NEXT:    store ptr [[B]], ptr [[TMP4]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = add i32 [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    call void @foo(i32 [[TMP6]], ptr [[TMP8]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
  %a = select i1 %cond, ptr %b, ptr %c

  call void @foo(i32 0, ptr %a);
  call void @foo(i32 1, ptr %a);
  call void @foo(i32 2, ptr %a);
  call void @foo(i32 3, ptr %b);
  ret void
}

; Make sure that we create correct stores for values used in many mismatching arrays
define void @values_used_in_many_mismatching_arrays(i1 %cond, ptr %b, ptr %c) {
; CHECK-LABEL: define void @values_used_in_many_mismatching_arrays(
; CHECK-SAME: i1 [[COND:%.*]], ptr [[B:%.*]], ptr [[C:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY1:%.*]] = alloca [4 x ptr], align 8
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [4 x ptr], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[COND]], ptr [[B]], ptr [[C]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store ptr [[C]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store ptr [[B]], ptr [[TMP2]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[B]], ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 3
; CHECK-NEXT:    store ptr [[B]], ptr [[TMP4]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY1]], i32 0, i32 0
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP5]], align 8
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY1]], i32 0, i32 1
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP6]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY1]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP7]], align 8
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY1]], i32 0, i32 3
; CHECK-NEXT:    store ptr [[B]], ptr [[TMP8]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY1]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[TMP11]], align 8
; CHECK-NEXT:    call void @baz(ptr [[TMP10]], ptr [[TMP12]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
  %a = select i1 %cond, ptr %b, ptr %c

  call void @baz(ptr %c, ptr %a);
  call void @baz(ptr %b, ptr %a);
  call void @baz(ptr %b, ptr %a);
  call void @baz(ptr %b, ptr %b);
  ret void
}

define void @no_alloca_in_loop(i1 %cond, ptr %b, ptr %c) {
; CHECK-LABEL: define void @no_alloca_in_loop(
; CHECK-SAME: i1 [[COND:%.*]], ptr [[B:%.*]], ptr [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [4 x ptr], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[COND]], ptr [[B]], ptr [[C]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 3
; CHECK-NEXT:    store ptr [[B]], ptr [[TMP4]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = add i32 [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [4 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    call void @foo(i32 [[TMP6]], ptr [[TMP8]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE]]
;
entry:
  br label %loop
loop:
  %a = select i1 %cond, ptr %b, ptr %c
  call void @foo(i32 0, ptr %a);
  call void @foo(i32 1, ptr %a);
  call void @foo(i32 2, ptr %a);
  call void @foo(i32 3, ptr %b);

  br label %loop
}

; Mismatching node with values in the function's parameter and previous block
define dso_local void @mismatching_node_param_prev_bb(ptr %x.addr, i32 %x, i32 %y, i1 %cond) {
; CHECK-LABEL: define dso_local void @mismatching_node_param_prev_bb(
; CHECK-SAME: ptr [[X_ADDR:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    [[Z:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i32 0, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[X]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store i32 [[Z]], ptr [[TMP3]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i32 [[TMP5]]
; CHECK-NEXT:    call void @bar(ptr [[TMP6]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
start:
  %z = add i32 %x, %y
  br label %entry

entry:
  %0 = load ptr, ptr %x.addr, align 8

  %add.ptr1 = getelementptr inbounds i32, ptr %0, i32 %x
  %add.ptr2 = getelementptr inbounds i32, ptr %0, i32 %z

  call void @bar(ptr %0)
  call void @bar(ptr %add.ptr1)
  call void @bar(ptr %add.ptr2)

  ret void
}

; Test for neutral pointers in different blocks
define dso_local void @neutral_ptrs_prev_bb(ptr %x.addr) {
; CHECK-LABEL: define dso_local void @neutral_ptrs_prev_bb(
; CHECK-SAME: ptr [[X_ADDR:%.*]]) {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x ptr], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8
; CHECK-NEXT:    [[ADD_PTR1:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i32 1
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store ptr [[ADD_PTR1]], ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP1]], ptr [[TMP4]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[TMP5]], align 8
; CHECK-NEXT:    call void @bar(ptr [[TMP6]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
start:
  %0 = load ptr, ptr %x.addr, align 8
  %add.ptr1 = getelementptr inbounds i32, ptr %0, i32 1
  br label %entry

entry:
  %add.ptr2 = getelementptr inbounds i32, ptr %0, i32 2

  call void @bar(ptr %0)
  call void @bar(ptr %add.ptr1)
  call void @bar(ptr %add.ptr2)

  ret void
}

; Test for matching nodes from different BBs
define dso_local void @foo2(ptr %x.addr, ptr %y.addr, ptr %z.addr) {
; CHECK-LABEL: define dso_local void @foo2(
; CHECK-SAME: ptr [[X_ADDR:%.*]], ptr [[Y_ADDR:%.*]], ptr [[Z_ADDR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x ptr], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[X_ADDR]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[Y_ADDR]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[Z_ADDR]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store ptr [[TMP1]], ptr [[TMP4]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[TMP2]], ptr [[TMP5]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[TMP6]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[TMP9]], i32 [[TMP7]]
; CHECK-NEXT:    call void @bar(ptr [[TMP10]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = load ptr, ptr %x.addr, align 8
  %1 = load ptr, ptr %y.addr, align 8
  br label %start

start:
  %2 = load ptr, ptr %z.addr, align 8

  call void @bar(ptr %0)

  %add.ptr1 = getelementptr inbounds i32, ptr %1, i32 1
  call void @bar(ptr %add.ptr1)

  %add.ptr2 = getelementptr inbounds i32, ptr %2, i32 2
  call void @bar(ptr %add.ptr2)

  ret void
}

define void @value_used_in_mismatching_and_external(ptr %ptr1, ptr %ptr2, ptr %ptr3) {
; CHECK-LABEL: define void @value_used_in_mismatching_and_external(
; CHECK-SAME: ptr [[PTR1:%.*]], ptr [[PTR2:%.*]], ptr [[PTR3:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x ptr], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store ptr [[PTR1]], ptr [[TMP0]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store ptr [[PTR2]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store ptr [[PTR3]], ptr [[TMP2]], align 8
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x ptr], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
; CHECK-NEXT:    call void @bar(ptr [[TMP4]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    call void @foo(i32 1, ptr [[PTR2]])
; CHECK-NEXT:    ret void
;
entry:
  call void @bar(ptr %ptr1)
  call void @bar(ptr %ptr2)
  call void @bar(ptr %ptr3)

  call void @foo(i32 1, ptr %ptr2)
  ret void
}


declare void @foo(i32, ptr)
declare void @bar(ptr)
declare void @baz(ptr, ptr)
