; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

define void @icmp_predicate_mismatch(i32 %0) {
; CHECK-LABEL: define void @icmp_predicate_mismatch(
; CHECK-SAME: i32 [[TMP0:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x i1], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = alloca i1, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ne i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x i1], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i1 [[TMP2]], ptr [[TMP5]], align 1
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [3 x i1], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i1 [[TMP3]], ptr [[TMP6]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [3 x i1], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store i1 [[TMP4]], ptr [[TMP7]], align 1
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr [3 x i1], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i1, ptr [[TMP8]], align 1
; CHECK-NEXT:    store i1 [[TMP9]], ptr [[TMP1]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %1 = alloca i1, align 4

  %2 = icmp eq i32 %0, 0
  store i1 %2, ptr %1

  %3 = icmp ne i32 %0, 0
  store i1 %3, ptr %1

  %4 = icmp eq i32 %0, 0
  store i1 %4, ptr %1

  ret void
}

define void @extractvalue_index_mismatch(ptr %p) {
; CHECK-LABEL: define void @extractvalue_index_mismatch(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x i64], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { i64, i64 } { i64 0, i64 1 }, 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i64, i64 } { i64 0, i64 1 }, 1
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { i64, i64 } { i64 0, i64 1 }, 0
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i64 [[TMP1]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP5]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [3 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i64, ptr [[TMP6]], align 4
; CHECK-NEXT:    store i64 [[TMP7]], ptr [[P]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = extractvalue { i64, i64 } { i64 0, i64 1}, 0
  store i64 %0, ptr %p

  %1 = extractvalue { i64, i64 } { i64 0, i64 1}, 1
  store i64 %1, ptr %p

  %2 = extractvalue { i64, i64 } { i64 0, i64 1}, 0
  store i64 %2, ptr %p

  ret void
}

define void @extractvalue_type_mismatch(ptr %p) {
; CHECK-LABEL: define void @extractvalue_type_mismatch(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x i64], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { i64, i64 } { i64 0, i64 1 }, 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i64, i32 } { i64 0, i32 1 }, 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { i64, i64 } { i64 0, i64 1 }, 0
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i64 [[TMP1]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP5]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [3 x i64], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i64, ptr [[TMP6]], align 4
; CHECK-NEXT:    store i64 [[TMP7]], ptr [[P]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = extractvalue { i64, i64 } { i64 0, i64 1}, 0
  store i64 %0, ptr %p

  %1 = extractvalue { i64, i32 } { i64 0, i32 1}, 0
  store i64 %1, ptr %p

  %2 = extractvalue { i64, i64 } { i64 0, i64 1}, 0
  store i64 %2, ptr %p

  ret void
}

define void @add_sign_flag_mismatch(i32 %a) {
; CHECK-LABEL: define void @add_sign_flag_mismatch(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i32 [[A]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[A]], 2
; CHECK-NEXT:    [[TMP2:%.*]] = add nuw i32 [[A]], 3
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[TMP5]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP6]], align 4
; CHECK-NEXT:    call void @bar(i32 [[TMP7]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = add nsw i32 %a, 1
  call void @bar(i32 %0)

  %2 = add i32 %a, 2
  call void @bar(i32 %2)

  %4 = add nuw i32 %a, 3
  call void @bar(i32 %4)

  ret void
}

declare void @bar(i32 %a)
