; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

define dso_local void @basic_store_call() {
; CHECK-LABEL: define dso_local void @basic_store_call() {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[TMP0]], 0
; CHECK-NEXT:    call void @bar(i32 noundef [[TMP1]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE3:.*]]
; CHECK:       [[LOOP_ROLLING_PRE3]]:
; CHECK-NEXT:    [[TMP2:%.*]] = alloca i32, align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY2:.*]]
; CHECK:       [[LOOP_ROLLING_BODY2]]:
; CHECK-NEXT:    [[IV5:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE3]] ], [ [[IV_NEXT6:%.*]], %[[LOOP_ROLLING_BODY2]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = mul i32 [[IV5]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = add i32 [[TMP3]], 0
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[IV_NEXT6]] = add i32 [[IV5]], 1
; CHECK-NEXT:    [[EXIT7:%.*]] = icmp ult i32 [[IV_NEXT6]], 3
; CHECK-NEXT:    br i1 [[EXIT7]], label %[[LOOP_ROLLING_BODY2]], label %[[LOOP_ROLLING_EXIT1:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT1]]:
; CHECK-NEXT:    ret void
;
begin:
  call void @bar(i32 noundef 0)
  call void @bar(i32 noundef 1)
  call void @bar(i32 noundef 2)
  br label %end

end:
  %a = alloca i32, align 4
  store i32 0, ptr %a, align 4
  store i32 1, ptr %a, align 4
  store i32 2, ptr %a, align 4
  ret void
}

declare void @bar(i32 noundef)
