; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

define i32 @phi_body_value_after_BB(i32 %x, i32 %y, i1 %cond) {
; CHECK-LABEL: define i32 @phi_body_value_after_BB(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    [[OUTPUT_MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP_ROLLING_PRE:.*]], label %[[BLOCK2:.*]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @bia(i32 [[X]], i32 [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[BLOCK2]]:
; CHECK-NEXT:    [[Z:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[RESULT:%.*]] = phi i32 [ [[TMP5]], %[[LOOP_ROLLING_EXIT]] ], [ [[Z]], %[[BLOCK2]] ]
; CHECK-NEXT:    ret i32 [[RESULT]]
;
start:
  br i1 %cond, label %block1, label %block2

block1:
  call i32 @bia(i32 %x, i32 0);
  call i32 @bia(i32 %x, i32 1);
  %call1 = call i32 @bia(i32 %x, i32 2);
  br label %merge

block2:
  %z = add i32 %x, %y
  br label %merge

merge:
  %result = phi i32 [ %call1, %block1 ], [ %z, %block2 ]
  ret i32 %result
}

define i32 @phi_preheader_value_after_BB(i1 %cond, i32 %val1, i32 %val2) {
; CHECK-LABEL: define i32 @phi_preheader_value_after_BB(
; CHECK-SAME: i1 [[COND:%.*]], i32 [[VAL1:%.*]], i32 [[VAL2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP_ROLLING_PRE:.*]], label %[[FALSE_BLOCK:.*]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[VAL1]], [[VAL2]]
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 0
; CHECK-NEXT:    call void @bar(i32 [[TMP0]], i32 [[TMP2]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    br label %[[MERGE_BLOCK:.*]]
; CHECK:       [[FALSE_BLOCK]]:
; CHECK-NEXT:    [[VAL4:%.*]] = mul i32 [[VAL1]], [[VAL2]]
; CHECK-NEXT:    br label %[[MERGE_BLOCK]]
; CHECK:       [[MERGE_BLOCK]]:
; CHECK-NEXT:    [[RESULT:%.*]] = phi i32 [ [[TMP0]], %[[LOOP_ROLLING_EXIT]] ], [ [[VAL4]], %[[FALSE_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[RESULT]]
;
entry:
  br i1 %cond, label %true_block, label %false_block

true_block:
  %val3 = add i32 %val1, %val2
  call void @bar(i32 %val3, i32 0);
  call void @bar(i32 %val3, i32 1);
  call void @bar(i32 %val3, i32 2);

  br label %merge_block

false_block:
  %val4 = mul i32 %val1, %val2
  br label %merge_block

merge_block:
  %result = phi i32 [ %val3, %true_block ], [ %val4, %false_block ]
  ret i32 %result
}

define i32 @phi_unused_in_AG_value(i1 %cond, i32 %val1, i32 %val2) {
; CHECK-LABEL: define i32 @phi_unused_in_AG_value(
; CHECK-SAME: i1 [[COND:%.*]], i32 [[VAL1:%.*]], i32 [[VAL2:%.*]]) {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    [[X:%.*]] = add i32 [[VAL1]], [[VAL2]]
; CHECK-NEXT:    br i1 [[COND]], label %[[BLOCK1:.*]], label %[[BLOCK2:.*]]
; CHECK:       [[BLOCK1]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK:       [[BLOCK2]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i32 [ [[VAL1]], %[[BLOCK1]] ], [ [[VAL2]], %[[BLOCK2]] ]
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 0
; CHECK-NEXT:    call void @bar(i32 [[X]], i32 [[TMP2]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret i32 [[TMP0]]
;
start:
  %x = add i32 %val1, %val2
  br i1 %cond, label %block1, label %block2

block1:
  br label %merge

block2:
  br label %merge

merge:
  %result = phi i32 [ %val1, %block1 ], [ %val2, %block2 ]
  call void @bar(i32 %x, i32 0);
  call void @bar(i32 %x, i32 1);
  call void @bar(i32 %x, i32 2);
  ret i32 %result
}

define i32 @phi_inside_BB_mismatching_value(i32 %x, i32 %y, i1 %cond) {
; CHECK-LABEL: define i32 @phi_inside_BB_mismatching_value(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    br i1 [[COND]], label %[[BLOCK1:.*]], label %[[BLOCK2:.*]]
; CHECK:       [[BLOCK1]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK:       [[BLOCK2]]:
; CHECK-NEXT:    [[Z:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i32 [ [[X]], %[[BLOCK1]] ], [ [[Y]], %[[BLOCK2]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i32 0, ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store i32 3, ptr [[TMP3]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
; CHECK-NEXT:    call void @bar(i32 [[X]], i32 [[TMP5]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret i32 [[TMP0]]
;
start:
  br i1 %cond, label %block1, label %block2

block1:
  br label %merge

block2:
  %z = add i32 %x, %y
  br label %merge

merge:
  %result = phi i32 [ %x, %block1 ], [ %y, %block2 ]
  call void @bar(i32 %x, i32 0);
  call void @bar(i32 %x, i32 %result);
  call void @bar(i32 %x, i32 3);
  ret i32 %result
}


define void @phi_inside_BB_matching_value(i32 %x, i32 %y, i1 %cond) {
; CHECK-LABEL: define void @phi_inside_BB_matching_value(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [2 x i32], align 4
; CHECK-NEXT:    br i1 [[COND]], label %[[BLOCK1:.*]], label %[[BLOCK2:.*]]
; CHECK:       [[BLOCK1]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK:       [[BLOCK2]]:
; CHECK-NEXT:    [[Z:%.*]] = add i32 [[X]], [[Y]]
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i32 [ [[X]], %[[BLOCK1]] ], [ [[Y]], %[[BLOCK2]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = phi i32 [ [[X]], %[[BLOCK1]] ], [ [[Z]], %[[BLOCK2]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [2 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [2 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[TMP3]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [2 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
; CHECK-NEXT:    call void @bar(i32 [[X]], i32 [[TMP5]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 2
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
start:
  br i1 %cond, label %block1, label %block2

block1:
  br label %merge

block2:
  %z = add i32 %x, %y
  br label %merge

merge:
  %result1 = phi i32 [ %x, %block1 ], [ %y, %block2 ]
  %result2 = phi i32 [ %x, %block1 ], [ %z, %block2 ]

  call void @bar(i32 %x, i32 %result1);
  call void @bar(i32 %x, i32 %result2);
  ret void
}

; Test for when a value in the phi node is used in Neutral Node but comes from the function's paramter
define dso_local void @phi_instruction_of_function_parameter(i32 %z, ptr %x.addr, ptr %y.addr, i1 %cond) {
; CHECK-LABEL: define dso_local void @phi_instruction_of_function_parameter(
; CHECK-SAME: i32 [[Z:%.*]], ptr [[X_ADDR:%.*]], ptr [[Y_ADDR:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [2 x i32], align 4
; CHECK-NEXT:    br i1 [[COND]], label %[[BLOCK1:.*]], label %[[BLOCK2:.*]]
; CHECK:       [[BLOCK1]]:
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[BLOCK2]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[RESULT:%.*]] = phi ptr [ [[X_ADDR]], %[[BLOCK1]] ], [ [[Y_ADDR]], %[[BLOCK2]] ]
; CHECK-NEXT:    br label %[[LOOP_ROLLING_PRE:.*]]
; CHECK:       [[LOOP_ROLLING_PRE]]:
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [2 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i32 0, ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [2 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[Z]], ptr [[TMP3]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr [2 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP0]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds ptr, ptr [[X_ADDR]], i32 [[TMP1]]
; CHECK-NEXT:    call void @baz(ptr [[TMP2]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 2
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
start:
  br i1 %cond, label %block1, label %block2

block1:
  br label %merge

block2:
  br label %merge

merge:
  %result = phi ptr [ %x.addr, %block1 ], [ %y.addr, %block2 ]
  br label %entry

entry:
  %addr = getelementptr inbounds ptr, ptr %x.addr, i32 %z

  call void @baz(ptr %x.addr)
  call void @baz(ptr %addr)
  ret void
}

declare void @baz(ptr)
declare void @bar(i32 %x, i32)
declare i32 @bia(i32, i32)
