; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

; XFAIL: true

define i32 @basic(ptr %a, ptr %b) {
; CHECK-LABEL: define void @basic(
; CHECK-SAME: i32 [[A1:%.*]], i32 [[A2:%.*]], i32 [[B1:%.*]], i32 [[B2:%.*]], i32 [[C1:%.*]], i32 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[0]], %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ [[0]], %[[ENTRY]] ], [ [[ACC_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 %a1, %a2
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = add nsw i32 [[MUL]], [[ACC]]
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 4
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret i32 [[ACC_NEXT]]
;
entry:

  %a0p = getelementptr i32, ptr %a, i32 0
  %b0p = getelementptr i32, ptr %b, i32 0
  %a0 = load i32, ptr %a0p
  %b0 = load i32, ptr %b0p

  %a1p = getelementptr i32, ptr %a, i32 1
  %b1p = getelementptr i32, ptr %b, i32 1
  %a1 = load i32, ptr %a1p
  %b1 = load i32, ptr %b1p

  %a2p = getelementptr i32, ptr %a, i32 2
  %b2p = getelementptr i32, ptr %b, i32 2
  %a2 = load i32, ptr %a2p
  %b2 = load i32, ptr %b2p

  %m1 = mul i32 %a0, %b0
  %m2 = mul i32 %a1, %b1
  %m3 = mul i32 %a2, %b2

  %m12 = add nsw i32 %m1, %m2
  %m123 = add nsw i32 %m12, %m3

  ret i32 %m123
}

define i32 @mismatching_add(i32 %a1, i32 %a2, i32 %b1, i32 %b2, i32 %c1, i32 %c2) {
entry:

  %a = mul i32 %a1, %a2
  %b = mul i32 %b1, %b2
  %c = mul i32 %c1, %c2

  %ab = add i32 %a, %b
  %abc = add nuw i32 %ab, %c

  ret i32 %abc
}

; Cannot reduce the add because an intermediate value is used
define i32 @intermediate_used(i32 %a1, i32 %a2, i32 %b1, i32 %b2, i32 %c1, i32 %c2) {
entry:

  %a = mul i32 %a1, %a2
  %b = mul i32 %b1, %b2
  %c = mul i32 %c1, %c2

  %ab = add i32 %a, %b
  %abc = add i32 %ab, %c

  call void @bar(i32 %ab)

  ret i32 %abc
}

declare void @bar(i32 %a)
