; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

define void @use_body_value_in_exit(i32 %a) {
; CHECK-LABEL: define void @use_body_value_in_exit(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[OUTPUT_MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    [[OUTPUT_MISMATCHING_ARRAY1:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[TMP0]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i32 [[A]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY1]], i32 0, i32 [[IV]]
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @bar(i32 [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[TMP5]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT2:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT2]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY1]], i32 0, i32 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP12]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP8]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[TMP10]], align 4
; CHECK-NEXT:    [[TMP11:%.*]] = mul nsw i32 [[TMP7]], 3
; CHECK-NEXT:    ret void
;
entry:
  %add = add nsw i32 %a, 1
  %call = call i32 @bar(i32 %add)

  %add1 = add nsw i32 %a, 2
  %add3 = add nsw i32 %a, 3

  %call2 = call i32 @bar(i32 %add1)
  %call4 = call i32 @bar(i32 %add3)

  %b = alloca i32, align 4
  store i32 %call4, ptr %b, align 4

  %mul = mul nsw i32 %add1, 3
  ret void
}

declare i32 @bar(i32 %x)
