; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

; Test for use of preheader value in succedding BB
define void @external_preheader_use(ptr %x.addr, i32 %a) {
; CHECK-LABEL: define void @external_preheader_use(
; CHECK-SAME: ptr [[X_ADDR:%.*]], i32 [[A:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i32 [[A]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[X_ADDR]], align 8
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    store i32 0, ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[TMP8]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    store i32 2, ptr [[TMP7]], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[TMP2]], i32 [[TMP4]]
; CHECK-NEXT:    call void @baz(ptr [[TMP5]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    br label %[[START:.*]]
; CHECK:       [[START]]:
; CHECK-NEXT:    [[B:%.*]] = mul nsw i32 [[TMP0]], 3
; CHECK-NEXT:    ret void
;
entry:
  %add = add nsw i32 %a, 1
  %0 = load ptr, ptr %x.addr, align 8

  call void @baz(ptr %0)

  %add.ptr1 = getelementptr inbounds i32, ptr %0, i32 %add
  call void @baz(ptr %add.ptr1)

  %add.ptr2 = getelementptr inbounds i32, ptr %0, i32 2
  call void @baz(ptr %add.ptr2)

  br label %start

start:
  %b = mul nsw i32 %add, 3
  ret void
}

; Test for use of exit value in succedding BB
define void @external_exit_use(i32 %a) {
; CHECK-LABEL: define void @external_exit_use(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[OUTPUT_MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[TMP0]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i32 [[A]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @bar(i32 [[TMP2]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY]], i32 0, i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = add nsw i32 [[TMP6]], 8
; CHECK-NEXT:    br label %[[START:.*]]
; CHECK:       [[START]]:
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP7]], 3
; CHECK-NEXT:    ret void
;
entry:
  %add = add nsw i32 %a, 1
  %tmp = add nsw i32 %add, 8
  %call = call i32 @bar(i32 %add)

  %add1 = add nsw i32 %a, 2
  %add3 = add nsw i32 %a, 3

  %call2 = call i32 @bar(i32 %add1)
  %call4 = call i32 @bar(i32 %add3)
  br label %start

start:
  %mul = mul nsw i32 %tmp, 3
  ret void
}

; Test for use of body value in succedding BB
define i32 @external_body_use(ptr %a) {
; CHECK-LABEL: define i32 @external_body_use(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    [[OUTPUT_MISMATCHING_ARRAY:%.*]] = alloca [3 x i32], align 4
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @bia(i32 [[TMP0]], i32 [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY]], i32 0, i32 [[IV]]
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP4]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[A]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT1:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT1]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [3 x i32], ptr [[OUTPUT_MISMATCHING_ARRAY]], i32 0, i32 2
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[TMP5]], align 4
; CHECK-NEXT:    br label %[[RETURN:.*]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP6]], 2
; CHECK-NEXT:    ret i32 [[ADD]]
;
entry:

  %0 = load i32, ptr %a, align 4
  %call = call i32 @bia(i32 %0, i32 0)
  store i32 %call, ptr %a, align 4

  %1 = load i32, ptr %a, align 4
  %call1 = call i32 @bia(i32 %1, i32 1)
  store i32 %call1, ptr %a, align 4

  %2 = load i32, ptr %a, align 4
  %call2 = call i32 @bia(i32 %2, i32 2)
  store i32 %call2, ptr %a, align 4
  br label %return

return:
  %add = add nsw i32 %call2, 2
  ret i32 %add
}

declare void @baz(ptr %x)
declare i32 @bar(i32 %x)
declare i32 @bia(i32, i32) #1
