; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-rolling < %s -loop-rolling-ignore-cost | FileCheck %s

define void @unrollable(ptr %str) {
; CHECK-LABEL: define void @unrollable(
; CHECK-SAME: ptr [[STR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void (ptr, ...) @p(ptr [[STR]])
; CHECK-NEXT:    call void (ptr, ...) @p(ptr [[STR]], i32 1)
; CHECK-NEXT:    call void (ptr, ...) @p(ptr [[STR]], i32 2)
; CHECK-NEXT:    ret void
;
entry:
  call void (ptr, ...) @p(ptr %str)
  call void (ptr, ...) @p(ptr %str, i32 1)
  call void (ptr, ...) @p(ptr %str, i32 2)

  ret void
}

define void @rollable(ptr %str) {
; CHECK-LABEL: define void @rollable(
; CHECK-SAME: ptr [[STR:%.*]]) {
; CHECK-NEXT:  [[LOOP_ROLLING_PRE:.*]]:
; CHECK-NEXT:    br label %[[LOOP_ROLLING_BODY:.*]]
; CHECK:       [[LOOP_ROLLING_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP_ROLLING_PRE]] ], [ [[IV_NEXT:%.*]], %[[LOOP_ROLLING_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = mul i32 [[IV]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[TMP0]], 0
; CHECK-NEXT:    call void (ptr, ...) @p(ptr [[STR]], i32 [[TMP1]])
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXIT:%.*]] = icmp ult i32 [[IV_NEXT]], 3
; CHECK-NEXT:    br i1 [[EXIT]], label %[[LOOP_ROLLING_BODY]], label %[[LOOP_ROLLING_EXIT:.*]]
; CHECK:       [[LOOP_ROLLING_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  call void (ptr, ...) @p(ptr %str, i32 0)
  call void (ptr, ...) @p(ptr %str, i32 1)
  call void (ptr, ...) @p(ptr %str, i32 2)

  ret void
}


declare void @p(ptr, ...)
